/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse and validate request body
    const body = await request.json();
    const { user_id: userId, session_id: sessionId } = body;
    
    // Validate required fields
    if (!userId) {
      return NextResponse.json(
        { success: false, message: 'User ID is required for Nexus match cancellation' },
        { status: 400 }
      );
    }
    
    user_id = userId;
    
    // If session_id is provided, update the chat session
    if (sessionId) {
      // First verify the session exists and belongs to this user
      const sessionCheck = await db_query(
        db,
        'SELECT * FROM chatsessions WHERE id = $1 AND (user1id = $2 OR user2id = $2)',
        [sessionId, userId]
      );
      
      if (sessionCheck.length === 0) {
        return NextResponse.json(
          { success: false, message: 'Nexus session not found or access denied' },
          { status: 404 }
        );
      }
      
      // Update the session to ended status with current timestamp
      await db_query(
        db,
        'UPDATE chatsessions SET status = $1, ended_at = NOW() WHERE id = $2',
        ['ended', sessionId]
      );
    }
    
    // Check if user preferences exist
    const existingPrefs = await db_query(
      db,
      'SELECT * FROM userpreferences WHERE userid = $1',
      [userId]
    );
    
    if (existingPrefs.length > 0) {
      // Update existing preferences to set is_available to false
      await db_query(
        db,
        'UPDATE userpreferences SET is_available = $1 WHERE userid = $2',
        [false, userId]
      );
    } else {
      // Create new preferences with is_available set to false
      await db_query(
        db,
        'INSERT INTO userpreferences (id, userid, is_available) VALUES ($1, $2, $3)',
        [crypto.randomUUID(), userId, false]
      );
    }
    
    const result = {
      success: true,
      message: sessionId 
        ? 'Nexus match session cancelled successfully' 
        : 'Nexus match search cancelled successfully'
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Nexus match cancellation error:', error);
    
    const result = {
      success: false,
      message: 'Failed to cancel Nexus match'
    };
    
    return NextResponse.json(result, { status: 500 });
  }
}
