/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

// ContactSubmit - POST endpoint to submit a contact form
export async function POST(request) {
  try {
    // Get database connection
    const db = await db_init();
    
    // Parse request body
    const { name, email, subject, message } = await request.json();

    // Validate required fields
    if (!name || !email || !message) {
      return NextResponse.json({
        success: false,
        message: 'Name, email, and message are required fields'
      }, { status: 400 });
    }

    // Basic email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return NextResponse.json({
        success: false,
        message: 'Please provide a valid email address'
      }, { status: 400 });
    }

    // Generate UUID
    const id = crypto.randomUUID();
    const createdAt = new Date().toISOString();

    // Insert new record
    await db_query(db,
      'INSERT INTO contactsubmissions (id, name, email, subject, message, status, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7)',
      [id, name, email, subject || '', message, 'new', createdAt]
    );

    // Fetch the created record
    const newRecord = await db_query(db,
      'SELECT * FROM contactsubmissions WHERE id = $1',
      [id]
    );

    const result = {
      success: true,
      message: 'Thank you for your message! We will get back to you soon.',
      data: newRecord[0]
    };

    return NextResponse.json(result);

  } catch (error) {
    console.error('Error submitting contact form:', error);
    return NextResponse.json({
      success: false,
      message: 'An error occurred while submitting your message'
    }, { status: 500 });
  }
}


