/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    const userid = searchParams.get('userid');
    
    // Validate required parameter
    if (!userid) {
      return NextResponse.json(
        { error: 'Nexus: userid parameter is required' },
        { status: 400 }
      );
    }
    
    // Query for active bans
    // A ban is active if it's permanent OR expires in the future
    const query = `
      SELECT id, userid, reason, expires_at, is_permanent
      FROM userbans
      WHERE userid = $1
        AND (is_permanent = true OR expires_at > NOW())
      ORDER BY banned_at DESC
      LIMIT 1
    `;
    
    const banRecords = await db_query(db, query, [userid]);
    
    let result;
    
    if (banRecords && banRecords.length > 0) {
      const ban = banRecords[0];
      result = {
        is_banned: true,
        reason: ban.reason,
        expires_at: ban.expires_at ? ban.expires_at.toISOString() : null,
        is_permanent: ban.is_permanent
      };
    } else {
      result = {
        is_banned: false
      };
    }
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Nexus: Error checking user ban status:', error);
    return NextResponse.json(
      { error: 'Nexus: Failed to check user ban status' },
      { status: 500 }
    );
  }
}
