/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function PUT(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse request body
    const body = await request.json();
    const { session_id, status, ended_by } = body;
    
    // Validate required fields
    if (!session_id) {
      return NextResponse.json(
        { error: 'Nexus: session_id is required' },
        { status: 400 }
      );
    }
    
    if (!status) {
      return NextResponse.json(
        { error: 'Nexus: status is required' },
        { status: 400 }
      );
    }
    
    // Validate status value
    const validStatuses = ['pending', 'active', 'ended'];
    if (!validStatuses.includes(status)) {
      return NextResponse.json(
        { error: 'Nexus: Invalid status. Must be one of: pending, active, ended' },
        { status: 400 }
      );
    }
    
    // Check if session exists and user has access
    const sessionCheck = await db_query(
      db,
      "SELECT * FROM chatsessions WHERE id = $1 AND (user1id = $2 OR user2id = $2)",
      [session_id, user_id]
    );
    
    if (!sessionCheck || sessionCheck.length === 0) {
      return NextResponse.json(
        { error: 'Nexus: Session not found or access denied' },
        { status: 404 }
      );
    }
    
    const currentSession = sessionCheck[0];
    
    // Build UPDATE query based on status
    let updateQuery;
    let updateParams;
    
    if (status === 'active') {
      // If status is 'active', update started_at if not already set
      if (!currentSession.started_at) {
        updateQuery = "UPDATE chatsessions SET status = $1, started_at = CURRENT_TIMESTAMP WHERE id = $2 RETURNING *";
        updateParams = [status, session_id];
      } else {
        updateQuery = "UPDATE chatsessions SET status = $1 WHERE id = $2 RETURNING *";
        updateParams = [status, session_id];
      }
    } else if (status === 'ended') {
      // If status is 'ended', update ended_at to current timestamp
      updateQuery = "UPDATE chatsessions SET status = $1, ended_at = CURRENT_TIMESTAMP WHERE id = $2 RETURNING *";
      updateParams = [status, session_id];
    } else {
      // For 'pending' or other valid statuses
      updateQuery = "UPDATE chatsessions SET status = $1 WHERE id = $2 RETURNING *";
      updateParams = [status, session_id];
    }
    
    // Execute update
    const updatedSession = await db_query(db, updateQuery, updateParams);
    
    if (!updatedSession || updatedSession.length === 0) {
      return NextResponse.json(
        { error: 'Nexus: Failed to update session status' },
        { status: 500 }
      );
    }
    
    // If status is 'ended' and ended_by is provided, update sessionmetadata
    if (status === 'ended' && ended_by) {
      // Check if metadata record exists
      const metadataCheck = await db_query(
        db,
        "SELECT * FROM sessionmetadata WHERE chatsessionsid = $1",
        [session_id]
      );
      
      if (metadataCheck && metadataCheck.length > 0) {
        // Update existing metadata
        await db_query(
          db,
          "UPDATE sessionmetadata SET ended_by = $1 WHERE chatsessionsid = $2",
          [ended_by, session_id]
        );
      } else {
        // Create new metadata record
        await db_query(
          db,
          "INSERT INTO sessionmetadata (id, chatsessionsid, ended_by) VALUES ($1, $2, $3)",
          [crypto.randomUUID(), session_id, ended_by]
        );
      }
    }
    
    const result = {
      success: true,
      session: {
        id: updatedSession[0].id,
        user1id: updatedSession[0].user1id,
        user2id: updatedSession[0].user2id,
        session_type: updatedSession[0].session_type,
        status: updatedSession[0].status,
        started_at: updatedSession[0].started_at,
        ended_at: updatedSession[0].ended_at
      }
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Nexus updateSessionStatus error:', error);
    return NextResponse.json(
      { error: 'Nexus: An error occurred while updating session status' },
      { status: 500 }
    );
  }
}
