/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

// ContactList - GET endpoint to retrieve all contact submissions (admin only)
export async function GET(request) {
  try {
    // Get database connection
    const db = await db_init();
    
    
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.isadmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

    
    // Get query parameters
    const { searchParams } = new URL(request.url);
    const status = searchParams.get('status');
    
    let query = 'SELECT id, name, email, subject, message, status, created_at FROM contactsubmissions';
    let countQuery = 'SELECT COUNT(*) as count FROM contactsubmissions';
    const params = [];
    
    // Apply status filter if provided
    if (status && ['new', 'read', 'replied', 'archived'].includes(status)) {
      query += ' WHERE status = $1';
      countQuery += ' WHERE status = $1';
      params.push(status);
    }
    
    query += ' ORDER BY created_at DESC';
    
    // Fetch all contact submissions
    const result = await db_query(db, query, params);

    // Get total count
    const countResult = await db_query(db, countQuery, params);
    const total = parseInt(countResult[0]?.count || 0);

    const responseData = {
      success: true,
      data: result || [],
      total: total
    };

    return NextResponse.json(responseData);

  } catch (error) {
    console.error('Error fetching contact submissions:', error);
    return NextResponse.json({
      success: false,
      message: 'An error occurred while fetching contact submissions'
    }, { status: 500 });
  }
}


