/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function GET(request) {
  // Initialize database connection
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    const placement = searchParams.get('placement');
    
    // Get current timestamp
    const now = new Date().toISOString();
    
    // Build query to get active advertisements with their images
    let query = `
      SELECT 
        a.id,
        a.title,
        a.ad_type,
        a.target_url,
        a.placement,
        a.impressions,
        a.clicks,
        ai.id as image_id,
        ai.image_url,
        ai.is_primary,
        ai.display_order,
        ai.caption
      FROM advertisements a
      LEFT JOIN advertisementimages ai ON a.id = ai.advertisementsid
      WHERE a.is_active = $1
        AND a.starts_at <= $2
        AND a.ends_at >= $3
    `;
    
    const queryParams = [true, now, now];
    let paramIndex = 4;
    
    // Add placement filter if provided
    if (placement) {
      query += ` AND a.placement = $${paramIndex}`;
      queryParams.push(placement);
      paramIndex++;
    }
    
    // Sort by display_order
    query += ` ORDER BY ai.display_order ASC, a.id ASC`;
    
    // Execute query
    const rows = await db_query(db, query, queryParams);
    
    // Group images by advertisement
    const adsMap = new Map();
    
    for (const row of rows) {
      if (!adsMap.has(row.id)) {
        adsMap.set(row.id, {
          id: row.id,
          title: row.title,
          ad_type: row.ad_type,
          target_url: row.target_url,
          placement: row.placement,
          impressions: row.impressions,
          clicks: row.clicks,
          images: []
        });
      }
      
      // Add image if it exists
      if (row.image_id) {
        adsMap.get(row.id).images.push({
          id: row.image_id,
          image_url: row.image_url,
          is_primary: row.is_primary,
          display_order: row.display_order,
          caption: row.caption
        });
      }
    }
    
    // Convert map to array
    const ads = Array.from(adsMap.values());
    
    const result = {
      success: true,
      ads: ads
    };
    
    return NextResponse.json(result);
  } catch (error) {
    console.error('Nexus - Error retrieving active advertisements:', error);
    return NextResponse.json(
      { 
        success: false, 
        ads: []
      }, 
      { status: 500 }
    );
  }
}
