/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse request body
    const body = await request.json();
    const { advertisement_id, interaction_type } = body;
    
    // Validate required fields
    if (!advertisement_id) {
      return NextResponse.json(
        { error: 'Advertisement ID is required for Nexus ad tracking' },
        { status: 400 }
      );
    }
    
    if (!interaction_type) {
      return NextResponse.json(
        { error: 'Interaction type is required for Nexus ad tracking' },
        { status: 400 }
      );
    }
    
    // Validate interaction_type value
    if (interaction_type !== 'impression' && interaction_type !== 'click') {
      return NextResponse.json(
        { error: 'Interaction type must be either "impression" or "click" for Nexus ad tracking' },
        { status: 400 }
      );
    }
    
    // Check if advertisement exists
    const checkQuery = "SELECT id FROM advertisements WHERE id = $1";
    const adResult = await db_query(db, checkQuery, [advertisement_id]);
    
    if (!adResult || adResult.length === 0) {
      return NextResponse.json(
        { error: 'Advertisement not found in Nexus system' },
        { status: 404 }
      );
    }
    
    // Update the appropriate counter based on interaction type
    const fieldToIncrement = interaction_type === 'impression' ? 'impressions' : 'clicks';
    const updateQuery = `UPDATE advertisements SET ${fieldToIncrement} = ${fieldToIncrement} + 1 WHERE id = $1`;
    
    await db_query(db, updateQuery, [advertisement_id]);
    
    const result = { success: true };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Nexus ad interaction tracking error:', error);
    return NextResponse.json(
      { error: 'Failed to record ad interaction in Nexus system' },
      { status: 500 }
    );
  }
}
