
/*
Sitepaige v1.0.0
WARNING: This file is automatically generated and should not be modified.
*/ 

import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'SysApp',
  description: 'Secure Next.js Application',
  icons: {
    icon: '/favicon.ico',
  },
  // Security-related meta tags
  other: {
    'X-UA-Compatible': 'IE=edge',
    'X-Content-Type-Options': 'nosniff',
    'X-Frame-Options': 'DENY',
    'X-XSS-Protection': '1; mode=block',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="classFontSize classFontType">
        {children}
      </body>
    </html>
  );
}