
/*
Sitepaige v1.0.0
WARNING: This file is automatically generated and should not be modified.
*/

export function makeDisplay(str: string): string {
  // Debug output to help identify undefined issues
  if (str === undefined || str === null) {
    return 'Unknown';
  }
  
  if (typeof str !== 'string') {
    return String(str);
  }
  
  // Check if string ends with 'List'
  let result = str;
  if (str.toLowerCase().endsWith(' list')) {
    // Remove 'List' from the end
    result = str.replace(' List', '').replace(' list', '');
    
    // Add 's' to the end if not already present
    if (!result.endsWith('s')) {
      result = result + 's';
    }

  }

  result = result.replace("_", " ");

  // Add spaces between capitalized words
  result = result.replace(/([A-Z])/g, ' $1').trim();

  return result;
}
