/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  // Parse request body
  const body = await request.json();
  const { reporter_userid, reported_userid, chatsessionsid, reason, description } = body;
  
  // Validate required fields
  if (!reporter_userid || !reported_userid || !chatsessionsid || !reason) {
    return NextResponse.json(
      { error: 'Missing required fields: reporter_userid, reported_userid, chatsessionsid, and reason are required for Nexus report submission' },
      { status: 400 }
    );
  }
  
  // Validate reason is one of the allowed values
  const validReasons = ['harassment', 'inappropriate_content', 'spam', 'underage', 'other'];
  if (!validReasons.includes(reason)) {
    return NextResponse.json(
      { error: 'Invalid reason. Nexus accepts the following reasons: harassment, inappropriate_content, spam, underage, or other' },
      { status: 400 }
    );
  }
  
  // Generate new UUID for the report
  const reportId = crypto.randomUUID();
  
  // Get current timestamp
  const createdAt = new Date().toISOString();
  
  // Set userid for user-specific table (reporter is the user creating this record)
  user_id = reporter_userid;
  
  try {
    // Insert new report record with pending status
    const query = `
      INSERT INTO reports (id, userid, reporter_userid, reported_userid, chatsessionsid, reason, description, status, created_at)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
    `;
    
    const params = [
      reportId,
      user_id,
      reporter_userid,
      reported_userid,
      chatsessionsid,
      reason,
      description || null,
      'pending',
      createdAt
    ];
    
    await db_query(db, query, params);
    
    // Prepare success response
    const result = {
      success: true,
      message: 'Report submitted successfully to Nexus. Our moderation team will review it shortly.',
      report_id: reportId
    };
    
    return NextResponse.json(result);
  } catch (error) {
    return NextResponse.json(
      { 
        success: false,
        message: 'Failed to submit report to Nexus. Please try again later.',
        error: error.message 
      },
      { status: 500 }
    );
  }
}
