/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

// ContactDelete - DELETE endpoint to delete a contact submission (admin only)
export async function DELETE(request) {
  try {
    // Get database connection
    const db = await db_init();
    
    
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.isadmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

    
    // Get query parameters
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');

    // Validate required fields
    if (!id) {
      return NextResponse.json({
        success: false,
        message: 'Contact submission ID is required'
      }, { status: 400 });
    }

    // Check if record exists
    const existingRecord = await db_query(db,
      'SELECT id FROM contactsubmissions WHERE id = $1',
      [id]
    );

    if (!existingRecord || existingRecord.length === 0) {
      return NextResponse.json({
        success: false,
        message: 'Contact submission not found'
      }, { status: 404 });
    }

    // Delete the record
    await db_query(db,
      'DELETE FROM contactsubmissions WHERE id = $1',
      [id]
    );

    const result = {
      success: true,
      message: 'Contact submission deleted successfully'
    };

    return NextResponse.json(result);

  } catch (error) {
    console.error('Error deleting contact submission:', error);
    return NextResponse.json({
      success: false,
      message: 'An error occurred while deleting the contact submission'
    }, { status: 500 });
  }
}


