/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse request body
    const body = await request.json();
    
    // Validate required fields
    if (!body.chatsessionsid) {
      return NextResponse.json({ error: 'Nexus: chatsessionsid is required' }, { status: 400 });
    }
    
    if (body.duration_seconds === undefined || body.duration_seconds === null) {
      return NextResponse.json({ error: 'Nexus: duration_seconds is required' }, { status: 400 });
    }
    
    // Validate duration_seconds is a number
    if (typeof body.duration_seconds !== 'number' || isNaN(body.duration_seconds)) {
      return NextResponse.json({ error: 'Nexus: duration_seconds must be a valid number' }, { status: 400 });
    }
    
    // Generate new UUID for the metadata record
    const metadataId = crypto.randomUUID();
    
    // Get current timestamp
    const createdAt = new Date();
    
    // Insert the session metadata
    const query = `
      INSERT INTO sessionmetadata 
      (id, userid, chatsessionsid, duration_seconds, user1_ip_hash, user2_ip_hash, 
       user1_country, user2_country, ended_by, created_at)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
    `;
    
    const params = [
      metadataId,
      user_id,
      body.chatsessionsid,
      body.duration_seconds,
      body.user1_ip_hash || null,
      body.user2_ip_hash || null,
      body.user1_country || null,
      body.user2_country || null,
      body.ended_by || null,
      createdAt
    ];
    
    await db_query(db, query, params);
    
    const result = {
      success: true,
      metadata_id: metadataId
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Nexus: Error saving session metadata:', error);
    return NextResponse.json(
      { error: 'Nexus: Failed to save session metadata' },
      { status: 500 }
    );
  }
}
