/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse request body
    const body = await request.json();
    const { user_id: requestUserId, preferred_chat_type, interests, language } = body;
    
    // Validate required fields
    if (!requestUserId) {
      return NextResponse.json({ 
        success: false, 
        error: 'user_id is required for Nexus matching service' 
      }, { status: 400 });
    }
    
    user_id = requestUserId;
    
    // Build query to find available users that match preferences
    let matchQuery = `
      SELECT id, userid, preferred_chat_type, interests, language 
      FROM userpreferences 
      WHERE is_available = true AND userid != $1
    `;
    const queryParams = [requestUserId];
    let paramIndex = 2;
    
    // Add preference matching conditions - match if preferences align or are not specified
    if (preferred_chat_type) {
      matchQuery += ` AND (preferred_chat_type = $${paramIndex} OR preferred_chat_type IS NULL)`;
      queryParams.push(preferred_chat_type);
      paramIndex++;
    }
    
    if (language) {
      matchQuery += ` AND (language = $${paramIndex} OR language IS NULL)`;
      queryParams.push(language);
      paramIndex++;
    }
    
    // If interests provided, try to find users with similar interests
    if (interests) {
      matchQuery += ` AND (interests ILIKE $${paramIndex} OR interests IS NULL)`;
      queryParams.push(`%${interests}%`);
      paramIndex++;
    }
    
    matchQuery += ` ORDER BY id LIMIT 1`;
    
    // Execute match query
    const matchResults = await db_query(db, matchQuery, queryParams);
    
    let result;
    
    if (matchResults && matchResults.length > 0) {
      // Match found - create chat session
      const matchedUser = matchResults[0];
      const sessionId = crypto.randomUUID();
      
      // Create chat session with pending status
      await db_query(db, `
        INSERT INTO chatsessions (id, userid, user1id, user2id, session_type, status, started_at)
        VALUES ($1, $2, $3, $4, $5, $6, NOW())
      `, [
        sessionId,
        requestUserId,
        requestUserId,
        matchedUser.userid,
        preferred_chat_type || 'text',
        'pending'
      ]);
      
      // Set both users as unavailable
      await db_query(db, `
        UPDATE userpreferences 
        SET is_available = false 
        WHERE userid IN ($1, $2)
      `, [requestUserId, matchedUser.userid]);
      
      result = {
        success: true,
        status: 'matched',
        session_id: sessionId,
        peer_id: matchedUser.userid
      };
    } else {
      // No match found - add user to waiting queue
      // Check if user preferences already exist
      const existingPrefs = await db_query(db, `
        SELECT id FROM userpreferences WHERE userid = $1
      `, [requestUserId]);
      
      if (existingPrefs && existingPrefs.length > 0) {
        // Update existing preferences and set as available
        await db_query(db, `
          UPDATE userpreferences 
          SET preferred_chat_type = $1, interests = $2, language = $3, is_available = true
          WHERE userid = $4
        `, [preferred_chat_type, interests, language, requestUserId]);
      } else {
        // Create new preferences record
        const prefId = crypto.randomUUID();
        await db_query(db, `
          INSERT INTO userpreferences (id, userid, preferred_chat_type, interests, language, is_available)
          VALUES ($1, $2, $3, $4, $5, true)
        `, [prefId, requestUserId, preferred_chat_type, interests, language]);
      }
      
      result = {
        success: true,
        status: 'waiting'
      };
    }
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Nexus matching service error:', error);
    return NextResponse.json({ 
      success: false,
      status: 'error',
      error: 'Nexus was unable to process your match request. Please try again.' 
    }, { status: 500 });
  }
}
