/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../Auth/auth';
import { store_file } from '../storage/files';
import { send_email } from '../storage/email';
import { db_init, db_query } from '../db';

// ContactUpdate - PUT endpoint to update a contact submission status (admin only)
export async function PUT(request) {
  try {
    // Get database connection
    const db = await db_init();
    
    
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.isadmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

    
    // Parse request body
    const { id, status } = await request.json();

    // Validate required fields
    if (!id) {
      return NextResponse.json({
        success: false,
        message: 'Contact submission ID is required'
      }, { status: 400 });
    }

    // Validate status value
    const validStatuses = ['new', 'read', 'replied', 'archived'];
    if (!status || !validStatuses.includes(status)) {
      return NextResponse.json({
        success: false,
        message: 'Invalid status. Must be one of: new, read, replied, archived'
      }, { status: 400 });
    }

    // Check if record exists
    const existingRecord = await db_query(db,
      'SELECT id FROM contactsubmissions WHERE id = $1',
      [id]
    );

    if (!existingRecord || existingRecord.length === 0) {
      return NextResponse.json({
        success: false,
        message: 'Contact submission not found'
      }, { status: 404 });
    }

    // Update the record
    await db_query(db,
      'UPDATE contactsubmissions SET status = $1 WHERE id = $2',
      [status, id]
    );

    // Fetch the updated record
    const updatedRecord = await db_query(db,
      'SELECT * FROM contactsubmissions WHERE id = $1',
      [id]
    );

    const result = {
      success: true,
      message: 'Contact submission status updated successfully',
      data: updatedRecord[0]
    };

    return NextResponse.json(result);

  } catch (error) {
    console.error('Error updating contact submission:', error);
    return NextResponse.json({
      success: false,
      message: 'An error occurred while updating the contact submission'
    }, { status: 500 });
  }
}


